import price_sets


def get_price_template(productPrices: dict, blendPurchasesPrices: dict, processPurchasesPrices: dict, Units: dict,
                       name: str):
    price_set_template = {"Products": [
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "LPG", "Description": "LPG",
         "Selected": "false", "Price": productPrices['LPG'], "PriceUnit": Units['LPG'], "RateUnit": "Vol%",
         "Rate": "null",
         "Number": 1,
         "Type": 0, "LPCode": "LPG", "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": "null",
         "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null", "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null", "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "LNA",
         "Description": "Naphtha",
         "Selected": "false", "Price": productPrices['Naphtha'], "PriceUnit": Units['Naphtha'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 2,
         "Type": 0, "LPCode": "LNA", "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": "null",
         "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null", "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null", "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "MOGHQ",
         "Description": "Mogas Prem 95", "Selected": "false", "Price": productPrices['Mogas Prem 95'],
         "PriceUnit": Units['Mogas Prem 95'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 3, "Type": 0, "LPCode": "MGH", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "MOGLQ",
         "Description": "Mogas Reg 92", "Selected": "false", "Price": productPrices['Mogas Reg 92'],
         "PriceUnit": Units['Mogas Reg 92'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 4, "Type": 0, "LPCode": "MGL", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "JET",
         "Description": "Jet-A1",
         "Selected": "false", "Price": productPrices['Jet-A1'], "PriceUnit": Units['Jet-A1'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 6,
         "Type": 0, "LPCode": "JET", "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": "null",
         "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null", "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null", "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "DIEHQ",
         "Description": "Diesel 10ppm S", "Selected": "false", "Price": productPrices['Diesel 10ppm S'],
         "PriceUnit": Units['Diesel 10ppm S'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 7, "Type": 0, "LPCode": "DSH", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "DIELQ",
         "Description": "Diesel 50ppm S", "Selected": "false", "Price": productPrices['Diesel 50ppm S'],
         "PriceUnit": Units['Diesel 50ppm S'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 8, "Type": 0, "LPCode": "DSL", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "HOLHQ",
         "Description": "Heating Oil 0.1% S", "Selected": "false", "Price": productPrices['Heating Oil 0.1% S'],
         "PriceUnit": Units['Heating Oil 0.1% S'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 9, "Type": 0, "LPCode": "HOH", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "HOLLQ",
         "Description": "Heating Oil 0.2% S", "Selected": "false", "Price": productPrices['Heating Oil 0.2% S'],
         "PriceUnit": Units['Heating Oil 0.2% S'],
         "RateUnit": "Vol%", "Rate": "null", "Number": 10, "Type": 0, "LPCode": "HOL", "MinRate": "null",
         "MaxRate": "null",
         "MinPer": "null", "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null",
         "CentsPerUSG": "null", "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null",
         "DollarPerMbtu": "null", "BBLS": "null", "DollarPerMT": "null", "Account": "null", "Location": "null",
         "Period": "null", "VariablePrice": "null", "IsDefault": "false", "HasProperties": "false", "IsSale": "false",
         "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FOULS",
         "Description": "Fuel Oil 0.5% S", "Selected": "false",
         "Price": productPrices['Fuel Oil 0.5% S'], "PriceUnit": Units['Fuel Oil 0.5% S'],
         "RateUnit": "Vol%", "Rate": "null", "Number": 11, "Type": 0, "LPCode": "FUS",
         "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": "null", "Group": "null",
         "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null", "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null", "DollarPerMT": "null", "Account": "null", "Location": "null",
         "Period": "null", "VariablePrice": "null", "IsDefault": "false", "HasProperties": "false",
         "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FOLHQ",
         "Description": "Fuel Oil 1% S", "Selected": "false", "Price": productPrices['Fuel Oil 1% S'],
         "PriceUnit": Units['Fuel Oil 1% S'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 12, "Type": 0, "LPCode": "FOH", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FOLLQ",
         "Description": "Fuel Oil 3.5% S", "Selected": "false", "Price": productPrices['Fuel Oil 3.5% S'],
         "PriceUnit": Units['Fuel Oil 3.5% S'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 13, "Type": 0, "LPCode": "FOL", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "ASP",
         "Description": "Bitumen",
         "Selected": "false", "Price": productPrices['Bitumen'], "PriceUnit": Units['Bitumen'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 14,
         "Type": 0, "LPCode": "ASP", "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": "null",
         "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null", "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null", "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "COKHQ",
         "Description": "Coke (HQ)", "Selected": "false", "Price": productPrices['Coke (HQ)'],
         "PriceUnit": Units['Coke (HQ)'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 15, "Type": 0, "LPCode": "CKH", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "COKLQ",
         "Description": "Coke (LQ)", "Selected": "false", "Price": productPrices['Coke (LQ)'],
         "PriceUnit": Units['Coke (LQ)'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 16, "Type": 0, "LPCode": "CKL", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "WVG",
         "Description": "Vac Gasoil", "Selected": "false", "Price": productPrices['Vac Gasoil'],
         "PriceUnit": Units['Vac Gasoil'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 17, "Type": 0, "LPCode": "WVG", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "ARS",
         "Description": "Atm Resid", "Selected": "false", "Price": productPrices['Atm Resid'],
         "PriceUnit": Units['Atm Resid'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 18, "Type": 0, "LPCode": "ARS", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"}], "BlendComponents": [
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSLPG",
         "Description": "Feedstock LPG", "Selected": "false", "Price": blendPurchasesPrices['Feedstock LPG'],
         "PriceUnit": Units['Feedstock LPG'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 101, "Type": 1, "LPCode": "LPG", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": 5.0, "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null", "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSLNA",
         "Description": "Feedstock Lt Naphtha", "Selected": "false",
         "Price": blendPurchasesPrices['Feedstock Lt Naphtha'],
         "PriceUnit": Units['Feedstock Lt Naphtha'],
         "RateUnit": "Vol%", "Rate": "null", "Number": 102, "Type": 1, "LPCode": "NAP", "MinRate": "null",
         "MaxRate": "null", "MinPer": "null", "MaxPer": 10.0, "Group": "null", "Vol": "null", "Wgt": "null",
         "SPG": "null",
         "CentsPerUSG": "null", "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null",
         "DollarPerMbtu": "null", "BBLS": "null", "DollarPerMT": "null", "Account": "null", "Location": "null",
         "Period": "null", "VariablePrice": "null", "IsDefault": "false", "HasProperties": "false", "IsSale": "false",
         "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSALK",
         "Description": "Feedstock Alkylate", "Selected": "false",
         "Price": blendPurchasesPrices['Feedstock Alkylate'],
         "PriceUnit": Units['Feedstock Alkylate'], "RateUnit": "Vol%", "Rate": "null", "Number": 103,
         "Type": 1,
         "LPCode": "ALK", "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": 10.0,
         "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null",
         "DollarPerMbtu": "null", "BBLS": "null", "DollarPerMT": "null", "Account": "null",
         "Location": "null", "Period": "null", "VariablePrice": "null", "IsDefault": "false",
         "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"}], "ProcessStreams": [
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSHNA",
         "Description": "Feedstock Hv Naphtha", "Selected": "false",
         "Price": processPurchasesPrices['Feedstock Hv Naphtha'], "PriceUnit": Units['Feedstock Hv Naphtha'],
         "RateUnit": "Vol%", "Rate": "null", "Number": 104, "Type": 2, "LPCode": "HNA", "MinRate": "null",
         "MaxRate": "null", "MinPer": "null", "MaxPer": 30.0, "Group": "null", "Vol": "null", "Wgt": "null",
         "SPG": "null",
         "CentsPerUSG": "null", "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null",
         "DollarPerMbtu": "null", "BBLS": "null", "DollarPerMT": "null", "Account": "null", "Location": "null",
         "Period": "null", "VariablePrice": "null", "IsDefault": "false", "HasProperties": "false", "IsSale": "false",
         "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSVGO",
         "Description": "Feedstock VGO", "Selected": "false",
         "Price": processPurchasesPrices['Feedstock VGO'], "PriceUnit": Units['Feedstock VGO'],
         "RateUnit": "Vol%", "Rate": "null", "Number": 105, "Type": 2, "LPCode": "VGO",
         "MinRate": "null", "MaxRate": "null", "MinPer": "null", "MaxPer": 30.0, "Group": "null",
         "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null", "Rev": "null",
         "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null", "DollarPerMT": "null", "Account": "null", "Location": "null",
         "Period": "null", "VariablePrice": "null", "IsDefault": "false", "HasProperties": "false",
         "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSCKF",
         "Description": "Coker feed", "Selected": "false", "Price": processPurchasesPrices['Coker feed'],
         "PriceUnit": Units['Coker feed'], "RateUnit": "Vol%",
         "Rate": "null", "Number": 106, "Type": 2, "LPCode": "CKF", "MinRate": "null", "MaxRate": "null",
         "MinPer": "null",
         "MaxPer": "null", "Group": "null", "Vol": "null", "Wgt": "null", "SPG": "null", "CentsPerUSG": "null",
         "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null", "DollarPerMbtu": "null",
         "BBLS": "null",
         "DollarPerMT": "null", "Account": "null", "Location": "null", "Period": "null", "VariablePrice": "null",
         "IsDefault": "false", "HasProperties": "false", "IsSale": "false", "HasSpecs": "false"},
        {"Seasons": [], "DestinationMaterials": [], "Properties": [], "ID": "null", "Code": "FSNGS",
         "Description": "Natural Gas for Fuel", "Selected": "false",
         "Price": processPurchasesPrices['Natural Gas for Fuel'], "PriceUnit": Units['Natural Gas for Fuel'],
         "RateUnit": "Vol%", "Rate": "null", "Number": 107, "Type": 2, "LPCode": "NGS", "MinRate": "null",
         "MaxRate": "null", "MinPer": "null", "MaxPer": 100.0, "Group": "null", "Vol": "null", "Wgt": "null",
         "SPG": "null",
         "CentsPerUSG": "null", "Rev": "null", "Value": "null", "DollarPerBBL": "null", "Cost": "null",
         "DollarPerMbtu": "null", "BBLS": "null", "DollarPerMT": "null", "Account": "null", "Location": "null",
         "Period": "null", "VariablePrice": "null", "IsDefault": "false", "HasProperties": "false", "IsSale": "false",
         "HasSpecs": "false"}], "Selected": "true", "IsAcctWide": "false",
        "ShowMinMax": "false", "SortOrder": 0, "MinMaxType": 0, "Name": name}
    return price_set_template


def create_and_post_price_set(productPrices: dict, blendPurchasesPrices: dict, processPurchasesPrices: dict,
                              Units: dict, name: str, region: str):
    x = price_sets.get_price_sets(region)
    try:
        priceid = int(x.query('Name == @name')['ID'].iloc[0])
        price_sets.put_price_set(region, priceid,
                                 get_price_template(productPrices, blendPurchasesPrices, processPurchasesPrices, Units,
                                                    name))
        return priceid
    except:
        price_sets.post_price_set(
            get_price_template(productPrices, blendPurchasesPrices, processPurchasesPrices, Units, name), region)
        x = price_sets.get_price_sets(region)
        priceid = int(x.query('Name == @name')['ID'].iloc[0])
        return priceid
