country_map = {
    "Albania": "AL",
    "Algeria": "DZ",
    "Angola": "AO",
    "Argentina": "AR",
    "Australia": "AU",
    "Azerbaijan": "AZ",
    "Bangladesh": "BD",
    "Brazil": "BR",
    "Brunei": "BN",
    "Cameroon": "CM",
    "Canada": "CA",
    "Chad": "TD",
    "China": "CN",
    "Colombia": "CO",
    "Congo": "CD",
    "Cuba": "CU",
    "Dem.Rep Of Congo": "CD",
    "Denmark": "DK",
    "Ecuador": "EC",
    "Egypt": "EG",
    "Equatorial Guinea": "GQ",
    "Gabon": "GA",
    "Germany": "DE",
    "Ghana": "GH",
    "Guatemala": "GT",
    "Guyana": "GUY",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast": "CI",
    "Kazakhstan": "KZ",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Libya": "LY",
    "Madagascar": "MG",
    "Malaysia": "MY",
    "Malta": "MT",
    "Mauritania": "MR",
    "Mexico": "MX",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nigeria": "NG",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Papua New Guinea": "PG",
    "Peru": "PE",
    "Philippines": "PH",
    "Qatar": "QA",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Singapore": "SG",
    "Sudan": "SD",
    "Syria": "SY",
    "Thailand": "TH",
    "Trinidad": "TT",
    "Tunisia": "TN",
    "Turkmenistan": "TM",
    "UAE": "AE",
    "UK": "GB",
    "USA": "US",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zaire": "ZR",
}
